import type { ModelSpec } from './types';
import { aspectParam, boolParam, enumParam, imageSizeParams, negativePrompt, numImages, referenceImages } from './params';

/**
 * Image model catalog. See `catalog.video.ts` for the conventions —
 * parameter keys are wire-format keys for the endpoint they target.
 */

const NANO_BANANA_RATIOS = [
  'auto',
  '21:9',
  '16:9',
  '3:2',
  '4:3',
  '5:4',
  '1:1',
  '4:5',
  '3:4',
  '2:3',
  '9:16',
] as const;

const GROK_RATIOS = ['2:1', '16:9', '4:3', '3:2', '1:1', '2:3', '3:4', '9:16', '1:2'] as const;

export const IMAGE_MODELS: ModelSpec[] = [
  // ── Google (via fal) ──────────────────────────────────────────────────────
  {
    id: 'fal:nano-banana-2',
    label: 'Nano Banana 2',
    vendor: 'Google',
    provider: 'fal',
    modality: 'image',
    description: 'Gemini 3.1 Flash Image — fast, excellent text rendering, up to 4K.',
    docs: 'https://fal.ai/models/fal-ai/nano-banana-2',
    capabilities: { images: [referenceImages(14, { label: 'Reference images' })], batch: true },
    routing: {
      kind: 'fal',
      text: 'fal-ai/nano-banana-2',
      image: 'fal-ai/nano-banana-2/edit',
      fields: { reference: 'image_urls' },
    },
    params: [
      aspectParam('aspect_ratio', NANO_BANANA_RATIOS, 'auto'),
      enumParam('resolution', 'Resolution', ['0.5K', '1K', '2K', '4K'], '1K'),
      numImages(4),
      enumParam('output_format', 'Format', ['png', 'jpeg', 'webp'], 'png'),
      enumParam('safety_tolerance', 'Safety Tolerance', ['1', '2', '3', '4', '5', '6'], '4', { wide: true }),
      boolParam('enable_web_search', 'Web Search Grounding', false),
    ],
  },
  {
    id: 'fal:nano-banana-pro',
    label: 'Nano Banana Pro',
    vendor: 'Google',
    provider: 'fal',
    modality: 'image',
    description: 'Gemini 3 Pro Image — highest-fidelity Google image model.',
    docs: 'https://fal.ai/models/fal-ai/nano-banana-pro',
    capabilities: { images: [referenceImages(14, { label: 'Reference images' })], batch: true },
    routing: {
      kind: 'fal',
      text: 'fal-ai/nano-banana-pro',
      image: 'fal-ai/nano-banana-pro/edit',
      fields: { reference: 'image_urls' },
    },
    params: [
      aspectParam('aspect_ratio', NANO_BANANA_RATIOS, '1:1'),
      enumParam('resolution', 'Resolution', ['1K', '2K', '4K'], '1K'),
      numImages(4),
      enumParam('output_format', 'Format', ['png', 'jpeg', 'webp'], 'png'),
      enumParam('safety_tolerance', 'Safety Tolerance', ['1', '2', '3', '4', '5', '6'], '4', { wide: true }),
      boolParam('enable_web_search', 'Web Search Grounding', false),
    ],
  },

  // ── OpenAI (via fal) ──────────────────────────────────────────────────────
  {
    id: 'fal:gpt-image-2',
    label: 'GPT Image 2',
    vendor: 'OpenAI',
    provider: 'fal',
    modality: 'image',
    description: 'OpenAI GPT Image 2 with transparency and quality control.',
    docs: 'https://fal.ai/models/openai/gpt-image-2',
    capabilities: { images: [referenceImages(10, { label: 'Reference images' })], batch: true },
    routing: {
      kind: 'fal',
      text: 'openai/gpt-image-2',
      image: 'openai/gpt-image-2/edit',
      fields: { reference: 'image_urls' },
      imageSize: { key: 'image_size', multipleOf: 16, minSide: 256, maxSide: 2048 },
    },
    params: [
      ...imageSizeParams(['1K', '2K'], '1K'),
      numImages(4),
      enumParam('quality', 'Quality', ['auto', 'low', 'medium', 'high'], 'high'),
      enumParam('background', 'Background', ['auto', 'transparent', 'opaque'], 'auto'),
      enumParam('output_format', 'Format', ['png', 'jpeg', 'webp'], 'png'),
    ],
  },
  {
    id: 'fal:gpt-image-2.5-flare',
    label: 'GPT Image 2.5 Flare',
    vendor: 'OpenAI',
    provider: 'fal',
    modality: 'image',
    description: 'GPT Image 2.5 Flare — newest OpenAI image model, up to "max" quality.',
    docs: 'https://fal.ai/models/openai/gpt-image-2.5/flare/text-to-image',
    capabilities: { images: [referenceImages(10, { label: 'Reference images' })], batch: true },
    routing: {
      kind: 'fal',
      text: 'openai/gpt-image-2.5/flare/text-to-image',
      image: 'openai/gpt-image-2.5/flare/edit',
      fields: { reference: 'image_urls' },
      imageSize: { key: 'image_size', multipleOf: 16, minSide: 256, maxSide: 2048 },
    },
    params: [
      ...imageSizeParams(['1K', '2K'], '1K'),
      numImages(10),
      enumParam('quality', 'Quality', ['auto', 'low', 'medium', 'high', 'xhigh', 'max'], 'high', { wide: true }),
      enumParam('background', 'Background', ['auto', 'transparent', 'opaque'], 'auto'),
      enumParam('output_format', 'Format', ['png', 'jpeg', 'webp'], 'png'),
    ],
  },
  {
    id: 'fal:gpt-image-2.5-sunburst',
    label: 'GPT Image 2.5 Sunburst',
    vendor: 'OpenAI',
    provider: 'fal',
    modality: 'image',
    description: 'GPT Image 2.5 Sunburst variant — alternate aesthetic tuning.',
    docs: 'https://fal.ai/models/openai/gpt-image-2.5/sunburst/text-to-image',
    capabilities: { images: [referenceImages(10, { label: 'Reference images' })], batch: true },
    routing: {
      kind: 'fal',
      text: 'openai/gpt-image-2.5/sunburst/text-to-image',
      image: 'openai/gpt-image-2.5/sunburst/edit',
      fields: { reference: 'image_urls' },
      imageSize: { key: 'image_size', multipleOf: 16, minSide: 256, maxSide: 2048 },
    },
    params: [
      ...imageSizeParams(['1K', '2K'], '1K'),
      numImages(10),
      enumParam('quality', 'Quality', ['auto', 'low', 'medium', 'high', 'xhigh', 'max'], 'high', { wide: true }),
      enumParam('background', 'Background', ['auto', 'transparent', 'opaque'], 'auto'),
      enumParam('output_format', 'Format', ['png', 'jpeg', 'webp'], 'png'),
    ],
  },

  // ── Black Forest Labs ─────────────────────────────────────────────────────
  {
    id: 'fal:flux-2-pro',
    label: 'FLUX 2 Pro',
    vendor: 'Black Forest Labs',
    provider: 'fal',
    modality: 'image',
    description: 'FLUX 2 Pro — photoreal detail with multi-reference editing.',
    docs: 'https://fal.ai/models/fal-ai/flux-2-pro',
    capabilities: { images: [referenceImages(10, { label: 'Reference images' })] },
    routing: {
      kind: 'fal',
      text: 'fal-ai/flux-2-pro',
      image: 'fal-ai/flux-2-pro/edit',
      fields: { reference: 'image_urls' },
      imageSize: { key: 'image_size', multipleOf: 16, minSide: 256, maxSide: 2560, maxArea: 4194304 },
    },
    params: [
      ...imageSizeParams(['1K', '2K'], '1K'),
      enumParam('output_format', 'Format', ['jpeg', 'png'], 'jpeg'),
      enumParam('safety_tolerance', 'Safety Tolerance', ['1', '2', '3', '4', '5'], '2', { wide: true }),
    ],
  },
  {
    id: 'fal:flux-2-max',
    label: 'FLUX 2 Max',
    vendor: 'Black Forest Labs',
    provider: 'fal',
    modality: 'image',
    badge: 'pro',
    description: 'Top FLUX 2 tier for maximum fidelity.',
    docs: 'https://fal.ai/models/fal-ai/flux-2-max',
    capabilities: { images: [referenceImages(10, { label: 'Reference images' })] },
    routing: {
      kind: 'fal',
      text: 'fal-ai/flux-2-max',
      image: 'fal-ai/flux-2-max/edit',
      fields: { reference: 'image_urls' },
      imageSize: { key: 'image_size', multipleOf: 16, minSide: 256, maxSide: 2560, maxArea: 4194304 },
    },
    params: [
      ...imageSizeParams(['1K', '2K'], '1K'),
      enumParam('output_format', 'Format', ['jpeg', 'png'], 'jpeg'),
      enumParam('safety_tolerance', 'Safety Tolerance', ['1', '2', '3', '4', '5'], '2', { wide: true }),
    ],
  },

  // ── ByteDance Seedream ────────────────────────────────────────────────────
  {
    id: 'fal:seedream-5-pro',
    label: 'Seedream 5.0 Pro',
    vendor: 'ByteDance',
    provider: 'fal',
    modality: 'image',
    description: 'Seedream 5.0 Pro — flagship ByteDance image model with strong editing.',
    docs: 'https://fal.ai/models/bytedance/seedream/v5/pro/text-to-image',
    capabilities: { images: [referenceImages(10, { label: 'Reference images' })], batch: true },
    routing: {
      kind: 'fal',
      text: 'bytedance/seedream/v5/pro/text-to-image',
      image: 'bytedance/seedream/v5/pro/edit',
      fields: { reference: 'image_urls' },
      imageSize: { key: 'image_size', minSide: 512, maxSide: 2048, maxArea: 4194304 },
    },
    params: [
      ...imageSizeParams(['1K', '2K'], '2K'),
      numImages(6),
      enumParam('output_format', 'Format', ['jpeg', 'png'], 'jpeg'),
    ],
  },
  {
    id: 'fal:seedream-4.5',
    label: 'Seedream 4.5',
    vendor: 'ByteDance',
    provider: 'fal',
    modality: 'image',
    description: 'Seedream 4.5 — fast, high-resolution generation and editing.',
    docs: 'https://fal.ai/models/fal-ai/bytedance/seedream/v4.5/text-to-image',
    capabilities: { images: [referenceImages(10, { label: 'Reference images' })], batch: true },
    routing: {
      kind: 'fal',
      text: 'fal-ai/bytedance/seedream/v4.5/text-to-image',
      image: 'fal-ai/bytedance/seedream/v4.5/edit',
      fields: { reference: 'image_urls' },
      imageSize: { key: 'image_size', minSide: 512, maxSide: 2048, maxArea: 4194304 },
    },
    params: [...imageSizeParams(['1K', '2K'], '2K'), numImages(6)],
  },

  // ── Alibaba ───────────────────────────────────────────────────────────────
  {
    id: 'fal:qwen-image-3',
    label: 'Qwen Image 3',
    vendor: 'Alibaba',
    provider: 'fal',
    modality: 'image',
    description: 'Qwen Image 3 with prompt expansion and negative prompts.',
    docs: 'https://fal.ai/models/alibaba/qwen-image-3/text-to-image',
    capabilities: { images: [referenceImages(10, { label: 'Reference images' })], batch: true },
    routing: {
      kind: 'fal',
      text: 'alibaba/qwen-image-3/text-to-image',
      image: 'alibaba/qwen-image-3/edit',
      fields: { reference: 'image_urls' },
      imageSize: { key: 'image_size', multipleOf: 16, minSide: 512, maxSide: 2048 },
    },
    params: [
      ...imageSizeParams(['1K', '2K'], '1K'),
      numImages(6),
      enumParam('output_format', 'Format', ['png', 'jpeg', 'webp'], 'png'),
      boolParam('enable_prompt_expansion', 'Prompt Expansion', true),
      negativePrompt(),
    ],
  },

  // ── Ideogram / Recraft / Krea / xAI ───────────────────────────────────────
  {
    id: 'fal:ideogram-v4',
    label: 'Ideogram V4',
    vendor: 'Ideogram',
    provider: 'fal',
    modality: 'image',
    description: 'Ideogram V4 — best-in-class typography and poster layouts.',
    docs: 'https://fal.ai/models/ideogram/v4',
    capabilities: { images: [], batch: true },
    routing: {
      kind: 'fal',
      text: 'ideogram/v4',
      imageSize: { key: 'image_size', multipleOf: 16, minSide: 512, maxSide: 3840 },
    },
    params: [
      ...imageSizeParams(['1K', '2K'], '1K'),
      numImages(4),
      enumParam('rendering_speed', 'Rendering Speed', ['TURBO', 'BALANCED', 'QUALITY'], 'BALANCED'),
      enumParam('expansion_model', 'Prompt Expansion', ['None', 'Medium', 'Large'], 'Medium'),
      enumParam('output_format', 'Format', ['jpeg', 'png'], 'jpeg'),
    ],
  },
  {
    id: 'fal:recraft-v4.1',
    label: 'Recraft V4.1',
    vendor: 'Recraft',
    provider: 'fal',
    modality: 'image',
    description: 'Recraft V4.1 — brand-consistent vectors, icons and illustration.',
    docs: 'https://fal.ai/models/fal-ai/recraft/v4.1/text-to-image',
    capabilities: { images: [] },
    routing: {
      kind: 'fal',
      text: 'fal-ai/recraft/v4.1/text-to-image',
      imageSize: { key: 'image_size', minSide: 512, maxSide: 2048 },
    },
    params: [...imageSizeParams(['1K', '2K'], '1K')],
  },
  {
    id: 'fal:krea-2',
    label: 'Krea 2 Large',
    vendor: 'Krea',
    provider: 'fal',
    modality: 'image',
    description: 'Krea 2 Large — art-directed aesthetics with creativity control.',
    docs: 'https://fal.ai/models/krea/v2/large/text-to-image',
    capabilities: { images: [] },
    routing: { kind: 'fal', text: 'krea/v2/large/text-to-image' },
    params: [
      aspectParam('aspect_ratio', ['1:1', '4:3', '3:2', '16:9', '2.35:1', '4:5', '2:3', '9:16'], '1:1'),
      enumParam('creativity', 'Creativity', ['raw', 'low', 'medium', 'high'], 'medium'),
    ],
  },
  {
    id: 'fal:grok-imagine-image-2',
    label: 'Grok Imagine Image 2.0',
    vendor: 'xAI',
    provider: 'fal',
    modality: 'image',
    description: 'xAI Grok Imagine 2.0 — fast generation and editing.',
    docs: 'https://fal.ai/models/xai/grok-imagine-image/v2.0/text-to-image',
    capabilities: { images: [referenceImages(4, { label: 'Reference images' })], batch: true },
    routing: {
      kind: 'fal',
      text: 'xai/grok-imagine-image/v2.0/text-to-image',
      image: 'xai/grok-imagine-image/v2.0/edit',
      fields: { reference: 'image_urls' },
    },
    params: [
      aspectParam('aspect_ratio', GROK_RATIOS, '1:1'),
      enumParam('resolution', 'Resolution', ['1k', '2k'], '1k'),
      enumParam('quality', 'Quality', ['low', 'medium'], 'medium'),
      numImages(4),
      enumParam('output_format', 'Format', ['jpeg', 'png', 'webp'], 'jpeg'),
    ],
  },

  // ── Direct provider APIs ──────────────────────────────────────────────────
  {
    id: 'google:gemini-3-pro-image',
    label: 'Nano Banana Pro',
    vendor: 'Google',
    provider: 'google',
    modality: 'image',
    description: 'Gemini 3 Pro Image straight from the Gemini API.',
    docs: 'https://ai.google.dev/gemini-api/docs/image-generation',
    capabilities: { images: [referenceImages(14, { label: 'Reference images' })], batch: true },
    routing: { kind: 'native', model: 'gemini-3-pro-image' },
    params: [
      aspectParam('aspectRatio', NANO_BANANA_RATIOS, 'auto'),
      enumParam('imageSize', 'Resolution', ['1K', '2K', '4K'], '1K'),
      numImages(4, 'numberOfImages'),
    ],
  },
  {
    id: 'google:gemini-3.1-flash-image',
    label: 'Nano Banana 2',
    vendor: 'Google',
    provider: 'google',
    modality: 'image',
    description: 'Gemini 3.1 Flash Image straight from the Gemini API.',
    docs: 'https://ai.google.dev/gemini-api/docs/image-generation',
    capabilities: { images: [referenceImages(14, { label: 'Reference images' })], batch: true },
    routing: { kind: 'native', model: 'gemini-3.1-flash-image' },
    params: [
      aspectParam('aspectRatio', NANO_BANANA_RATIOS, 'auto'),
      enumParam('imageSize', 'Resolution', ['512', '1K', '2K', '4K'], '1K'),
      numImages(4, 'numberOfImages'),
    ],
  },
  {
    id: 'google:gemini-3.1-flash-lite-image',
    label: 'Nano Banana 2 Lite',
    vendor: 'Google',
    provider: 'google',
    modality: 'image',
    badge: 'budget',
    description: 'Cheapest Gemini image model, 512px–2K.',
    docs: 'https://ai.google.dev/gemini-api/docs/image-generation',
    capabilities: { images: [referenceImages(14, { label: 'Reference images' })], batch: true },
    routing: { kind: 'native', model: 'gemini-3.1-flash-lite-image' },
    params: [
      aspectParam('aspectRatio', NANO_BANANA_RATIOS, 'auto'),
      enumParam('imageSize', 'Resolution', ['512', '1K', '2K'], '1K'),
      numImages(4, 'numberOfImages'),
    ],
  },
  {
    id: 'openai:gpt-image-2',
    label: 'GPT Image 2',
    vendor: 'OpenAI',
    provider: 'openai',
    modality: 'image',
    description: 'GPT Image 2 through the OpenAI images API using your OpenAI key.',
    docs: 'https://platform.openai.com/docs/api-reference/images',
    capabilities: { images: [referenceImages(10, { label: 'Reference images' })], batch: true },
    routing: { kind: 'native', model: 'gpt-image-2' },
    params: [
      enumParam('size', 'Size', ['auto', '1024x1024', '1536x1024', '1024x1536'], 'auto', { control: 'select' }),
      numImages(10, 'n'),
      enumParam('quality', 'Quality', ['auto', 'low', 'medium', 'high'], 'auto'),
      enumParam('background', 'Background', ['auto', 'transparent', 'opaque'], 'auto'),
      enumParam('output_format', 'Format', ['png', 'jpeg', 'webp'], 'png'),
      enumParam('moderation', 'Moderation', ['auto', 'low'], 'auto'),
      enumParam('input_fidelity', 'Input Fidelity', ['low', 'high'], 'low', {
        help: 'How closely edits preserve the reference image.',
      }),
    ],
  },
  {
    id: 'openai:gpt-image-2.5-flare',
    label: 'GPT Image 2.5 Flare',
    vendor: 'OpenAI',
    provider: 'openai',
    modality: 'image',
    description: 'GPT Image 2.5 Flare through the OpenAI images API.',
    docs: 'https://platform.openai.com/docs/api-reference/images',
    capabilities: { images: [referenceImages(10, { label: 'Reference images' })], batch: true },
    routing: { kind: 'native', model: 'gpt-image-2.5-flare' },
    params: [
      enumParam('size', 'Size', ['auto', '1024x1024', '1536x1024', '1024x1536'], 'auto', { control: 'select' }),
      numImages(10, 'n'),
      enumParam('quality', 'Quality', ['auto', 'low', 'medium', 'high', 'xhigh', 'max'], 'auto', { wide: true }),
      enumParam('background', 'Background', ['auto', 'transparent', 'opaque'], 'auto'),
      enumParam('output_format', 'Format', ['png', 'jpeg', 'webp'], 'png'),
      enumParam('moderation', 'Moderation', ['auto', 'low'], 'auto'),
    ],
  },
  {
    id: 'modelark:seedream-5-pro',
    label: 'Seedream 5.0 Pro',
    vendor: 'ByteDance',
    provider: 'modelark',
    modality: 'image',
    description: 'Seedream 5.0 Pro straight from BytePlus ModelArk.',
    docs: 'https://docs.byteplus.com/en/docs/ModelArk/1541523',
    capabilities: { images: [referenceImages(10, { label: 'Reference images' })], batch: true },
    routing: { kind: 'native', model: 'dola-seedream-5-0-pro-260628' },
    params: [
      enumParam('size', 'Resolution', ['1K', '2K', '4K'], '2K'),
      enumParam('output_format', 'Format', ['jpeg', 'png'], 'jpeg'),
      enumParam('background', 'Background', ['opaque', 'transparent'], 'opaque'),
      boolParam('watermark', 'Watermark', false),
    ],
  },
  {
    id: 'modelark:seedream-4.5',
    label: 'Seedream 4.5',
    vendor: 'ByteDance',
    provider: 'modelark',
    modality: 'image',
    description: 'Seedream 4.5 from BytePlus ModelArk, with batch generation.',
    docs: 'https://docs.byteplus.com/en/docs/ModelArk/1541523',
    capabilities: { images: [referenceImages(10, { label: 'Reference images' })], batch: true },
    routing: { kind: 'native', model: 'seedream-4-5-251128' },
    params: [
      enumParam('size', 'Resolution', ['1K', '2K', '4K'], '2K'),
      numImages(6, 'max_images'),
      enumParam('output_format', 'Format', ['jpeg', 'png'], 'jpeg'),
      boolParam('watermark', 'Watermark', false),
    ],
  },
  {
    id: 'kling:image-v3',
    label: 'Kling Image v3',
    vendor: 'Kuaishou',
    provider: 'kling',
    modality: 'image',
    description: 'Kling v3 image generation via the official API (dev proxy required).',
    docs: 'https://kling.ai/document-api/api/image/3-0-omni/image-generation',
    capabilities: { images: [referenceImages(1, { label: 'Reference images' })], batch: true },
    routing: { kind: 'native', model: 'kling-v3' },
    params: [
      aspectParam('aspect_ratio', ['16:9', '9:16', '1:1', '4:3', '3:4', '3:2', '2:3', '21:9'], '1:1'),
      numImages(9, 'n'),
      negativePrompt(),
    ],
  },
];
