import type { ModelSpec } from './types';
import {
  aspectParam,
  boolParam,
  durationChoices,
  durationEnum,
  durationSelect,
  endFrame,
  enumParam,
  negativePrompt,
  numberParam,
  referenceImages,
  safetyChecker,
  seedParam,
  startFrame,
} from './params';

/**
 * Video model catalog.
 *
 * Parameter keys match the wire format of the endpoint they target, so the
 * adapters can forward them verbatim. Enums, defaults and the per-role image
 * fields are transcribed from each provider's published schema — run
 * `npm run verify:models` to re-check the fal half against the live schemas.
 *
 * A parameter may appear twice with disjoint `omitFor` sets when an endpoint
 * accepts different values on different routes (see Grok's resolution).
 */

const SEEDANCE_DURATIONS = ['auto', '4', '5', '6', '8', '10', '12', '15', '20', '25', '30'] as const;
const SEEDANCE_2_0_DURATIONS = ['auto', '4', '5', '6', '8', '10', '12', '15'] as const;
const SEEDANCE_RATIOS = ['auto', '21:9', '16:9', '4:3', '1:1', '3:4', '9:16'] as const;
const KLING_DURATIONS = ['3', '4', '5', '6', '8', '10', '12', '15'] as const;
const KLING_RATIOS = ['16:9', '9:16', '1:1'] as const;
const VEO_DURATIONS = ['4s', '6s', '8s'] as const;
const VEO_RATIOS = ['16:9', '9:16'] as const;
const SAFETY_TOLERANCE = ['1', '2', '3', '4', '5', '6'] as const;
const MINIMAX_RATIOS = ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'] as const;
const WAN_RATIOS = ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16'] as const;

export const VIDEO_MODELS: ModelSpec[] = [
  // ── ByteDance Seedance ────────────────────────────────────────────────────
  {
    id: 'fal:seedance-2.5',
    label: 'Seedance 2.5',
    vendor: 'ByteDance',
    provider: 'fal',
    modality: 'video',
    description: 'Latest Seedance. Up to 30s, native audio, 1080p, first/last frame and multi-reference.',
    docs: 'https://fal.ai/models/bytedance/seedance-2.5/text-to-video',
    capabilities: { images: [startFrame(), endFrame(), referenceImages(10)], audio: true },
    routing: {
      kind: 'fal',
      text: 'bytedance/seedance-2.5/text-to-video',
      image: 'bytedance/seedance-2.5/image-to-video',
      reference: 'bytedance/seedance-2.5/reference-to-video',
      fields: { start: 'image_url', end: 'end_image_url', reference: 'image_urls' },
      extra: { task: 'reference' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['480p', '720p', '1080p'], '720p'),
      durationEnum(SEEDANCE_DURATIONS, 'auto'),
      aspectParam('aspect_ratio', SEEDANCE_RATIOS, 'auto', {
        omitFor: ['i2x'],
        help: 'Image-to-video follows the start frame.',
      }),
      boolParam('generate_audio', 'Generate Audio', true),
      enumParam('bitrate_mode', 'Bitrate', ['standard', 'high'], 'standard'),
      seedParam({ omitFor: ['t2x', 'i2x'] }),
    ],
  },
  {
    id: 'fal:seedance-2.0',
    label: 'Seedance 2.0',
    vendor: 'ByteDance',
    provider: 'fal',
    modality: 'video',
    description: 'Previous-generation Seedance with 4K output, native audio and multi-reference.',
    docs: 'https://fal.ai/models/bytedance/seedance-2.0/text-to-video',
    capabilities: { images: [startFrame(), endFrame(), referenceImages(10)], audio: true },
    routing: {
      kind: 'fal',
      text: 'bytedance/seedance-2.0/text-to-video',
      image: 'bytedance/seedance-2.0/image-to-video',
      reference: 'bytedance/seedance-2.0/reference-to-video',
      fields: { start: 'image_url', end: 'end_image_url', reference: 'image_urls' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['480p', '720p', '1080p', '4k'], '720p'),
      durationEnum(SEEDANCE_2_0_DURATIONS, 'auto'),
      aspectParam('aspect_ratio', SEEDANCE_RATIOS, 'auto'),
      boolParam('generate_audio', 'Generate Audio', true),
      enumParam('bitrate_mode', 'Bitrate', ['standard', 'high'], 'standard'),
    ],
  },

  // ── Kling ─────────────────────────────────────────────────────────────────
  {
    id: 'fal:kling-v3-pro',
    label: 'Kling v3 Pro',
    vendor: 'Kuaishou',
    provider: 'fal',
    modality: 'video',
    badge: 'pro',
    description: 'Kling 3.0 Pro with native audio, shot control and first/last frames.',
    docs: 'https://fal.ai/models/fal-ai/kling-video/v3/pro/text-to-video',
    capabilities: { images: [startFrame(), endFrame()], audio: true },
    routing: {
      kind: 'fal',
      text: 'fal-ai/kling-video/v3/pro/text-to-video',
      image: 'fal-ai/kling-video/v3/pro/image-to-video',
      fields: { start: 'start_image_url', end: 'end_image_url' },
    },
    params: [
      durationEnum(KLING_DURATIONS, '5'),
      aspectParam('aspect_ratio', KLING_RATIOS, '16:9', { omitFor: ['i2x'] }),
      enumParam('shot_type', 'Shot Type', ['customize', 'intelligent'], 'customize'),
      numberParam('cfg_scale', 'Prompt Adherence', 0, 1, 0.5, { step: 0.05 }),
      boolParam('generate_audio', 'Generate Audio', true),
      negativePrompt('blur, distort, and low quality'),
    ],
  },
  {
    id: 'fal:kling-v3-standard',
    label: 'Kling v3 Standard',
    vendor: 'Kuaishou',
    provider: 'fal',
    modality: 'video',
    description: 'Cheaper Kling 3.0 tier with the same controls as Pro.',
    docs: 'https://fal.ai/models/fal-ai/kling-video/v3/standard/text-to-video',
    capabilities: { images: [startFrame(), endFrame()], audio: true },
    routing: {
      kind: 'fal',
      text: 'fal-ai/kling-video/v3/standard/text-to-video',
      image: 'fal-ai/kling-video/v3/standard/image-to-video',
      fields: { start: 'start_image_url', end: 'end_image_url' },
    },
    params: [
      durationEnum(KLING_DURATIONS, '5'),
      aspectParam('aspect_ratio', KLING_RATIOS, '16:9', { omitFor: ['i2x'] }),
      enumParam('shot_type', 'Shot Type', ['customize', 'intelligent'], 'customize'),
      numberParam('cfg_scale', 'Prompt Adherence', 0, 1, 0.5, { step: 0.05 }),
      boolParam('generate_audio', 'Generate Audio', true),
      negativePrompt('blur, distort, and low quality'),
    ],
  },
  {
    id: 'fal:kling-o3-pro',
    label: 'Kling O3 Pro',
    vendor: 'Kuaishou',
    provider: 'fal',
    modality: 'video',
    badge: 'pro',
    description: 'Kling O3 reasoning-driven cinematography, with frames or references.',
    docs: 'https://fal.ai/models/fal-ai/kling-video/o3/pro/text-to-video',
    capabilities: { images: [startFrame(), endFrame(), referenceImages(4)], audio: true },
    routing: {
      kind: 'fal',
      text: 'fal-ai/kling-video/o3/pro/text-to-video',
      image: 'fal-ai/kling-video/o3/pro/image-to-video',
      reference: 'fal-ai/kling-video/o3/pro/reference-to-video',
      fields: { start: 'image_url', end: 'end_image_url', reference: 'image_urls' },
    },
    params: [
      durationEnum(KLING_DURATIONS, '5'),
      aspectParam('aspect_ratio', KLING_RATIOS, '16:9', { omitFor: ['i2x'] }),
      enumParam('shot_type', 'Shot Type', ['customize', 'intelligent'], 'customize'),
      boolParam('generate_audio', 'Generate Audio', false),
    ],
  },

  // ── Google ────────────────────────────────────────────────────────────────
  {
    id: 'fal:veo-3.1',
    label: 'Veo 3.1',
    vendor: 'Google',
    provider: 'fal',
    modality: 'video',
    description: "Google's Veo 3.1 with synced audio, up to 4K, and up to 3 asset references.",
    docs: 'https://fal.ai/models/fal-ai/veo3.1',
    capabilities: { images: [startFrame(), referenceImages(3)], audio: true },
    routing: {
      kind: 'fal',
      text: 'fal-ai/veo3.1',
      image: 'fal-ai/veo3.1/image-to-video',
      reference: 'fal-ai/veo3.1/reference-to-video',
      fields: { start: 'image_url', reference: 'image_urls' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['720p', '1080p', '4k'], '720p'),
      durationSelect('duration', VEO_DURATIONS, '8s', { labels: { '4s': '4s', '6s': '6s', '8s': '8s' } }),
      aspectParam('aspect_ratio', VEO_RATIOS, '16:9', { omitFor: ['i2x'] }),
      boolParam('generate_audio', 'Generate Audio', true),
      boolParam('auto_fix', 'Auto-fix Prompt', true),
      enumParam('safety_tolerance', 'Safety Tolerance', SAFETY_TOLERANCE, '4', { wide: true }),
      negativePrompt('', { omitFor: ['ref'] }),
      seedParam({ omitFor: ['ref'] }),
    ],
  },
  {
    id: 'fal:veo-3.1-fast',
    label: 'Veo 3.1 Fast',
    vendor: 'Google',
    provider: 'fal',
    modality: 'video',
    badge: 'fast',
    description: 'Lower-latency, lower-cost Veo 3.1.',
    docs: 'https://fal.ai/models/fal-ai/veo3.1/fast',
    capabilities: { images: [startFrame(), referenceImages(3)], audio: true },
    routing: {
      kind: 'fal',
      text: 'fal-ai/veo3.1/fast',
      image: 'fal-ai/veo3.1/fast/image-to-video',
      reference: 'fal-ai/veo3.1/fast/reference-to-video',
      fields: { start: 'image_url', reference: 'image_urls' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['720p', '1080p', '4k'], '720p'),
      durationSelect('duration', VEO_DURATIONS, '8s'),
      aspectParam('aspect_ratio', VEO_RATIOS, '16:9', { omitFor: ['i2x'] }),
      boolParam('generate_audio', 'Generate Audio', true),
      boolParam('auto_fix', 'Auto-fix Prompt', true),
      enumParam('safety_tolerance', 'Safety Tolerance', SAFETY_TOLERANCE, '4', { wide: true }),
      negativePrompt('', { omitFor: ['ref'] }),
      seedParam({ omitFor: ['ref'] }),
    ],
  },
  {
    id: 'fal:veo-3.1-lite',
    label: 'Veo 3.1 Lite',
    vendor: 'Google',
    provider: 'fal',
    modality: 'video',
    badge: 'budget',
    description: 'Cheapest Veo 3.1 tier, 720p or 1080p.',
    docs: 'https://fal.ai/models/fal-ai/veo3.1/lite',
    capabilities: { images: [startFrame()], audio: true },
    routing: {
      kind: 'fal',
      text: 'fal-ai/veo3.1/lite',
      image: 'fal-ai/veo3.1/lite/image-to-video',
      fields: { start: 'image_url' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['720p', '1080p'], '720p'),
      durationSelect('duration', VEO_DURATIONS, '8s'),
      aspectParam('aspect_ratio', VEO_RATIOS, '16:9', { omitFor: ['i2x'] }),
      boolParam('generate_audio', 'Generate Audio', true),
      boolParam('auto_fix', 'Auto-fix Prompt', true),
      enumParam('safety_tolerance', 'Safety Tolerance', SAFETY_TOLERANCE, '4', { wide: true }),
      negativePrompt(),
      seedParam(),
    ],
  },
  {
    id: 'fal:gemini-omni-flash-1.1',
    label: 'Gemini Omni Flash 1.1',
    vendor: 'Google',
    provider: 'fal',
    modality: 'video',
    description: 'Gemini Omni Flash video: 3–10s up to 4K, frames or references.',
    docs: 'https://fal.ai/models/google/gemini-omni-flash/v1.1/text-to-video',
    capabilities: { images: [startFrame(), endFrame(), referenceImages(4)], audio: true },
    routing: {
      kind: 'fal',
      text: 'google/gemini-omni-flash/v1.1/text-to-video',
      image: 'google/gemini-omni-flash/v1.1/image-to-video',
      reference: 'google/gemini-omni-flash/v1.1/reference-to-video',
      fields: { start: 'image_url', end: 'end_image_url', reference: 'image_urls' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['360p', '720p', '1080p', '4k'], '720p'),
      durationChoices([3, 4, 5, 6, 7, 8, 9, 10], 8),
      aspectParam('aspect_ratio', VEO_RATIOS, '16:9'),
    ],
  },

  // ── OpenAI ────────────────────────────────────────────────────────────────
  {
    id: 'fal:sora-2',
    label: 'Sora 2',
    vendor: 'OpenAI',
    provider: 'fal',
    modality: 'video',
    description: 'OpenAI Sora 2 with dialogue and sound, 4–20s.',
    docs: 'https://fal.ai/models/fal-ai/sora-2/text-to-video',
    capabilities: { images: [startFrame()], audio: true },
    routing: {
      kind: 'fal',
      text: 'fal-ai/sora-2/text-to-video',
      image: 'fal-ai/sora-2/image-to-video',
      fields: { start: 'image_url' },
    },
    params: [
      durationChoices([4, 8, 12, 16, 20], 4),
      aspectParam('aspect_ratio', VEO_RATIOS, '16:9', { omitFor: ['i2x'] }),
      enumParam('resolution', 'Resolution', ['720p'], '720p', { omitFor: ['i2x'] }),
    ],
  },

  // ── MiniMax ───────────────────────────────────────────────────────────────
  {
    id: 'fal:minimax-h3-max',
    label: 'MiniMax H3 Max',
    vendor: 'MiniMax',
    provider: 'fal',
    modality: 'video',
    description: 'H3 Max — MiniMax flagship, strong prompt adherence, 5–15s.',
    docs: 'https://fal.ai/models/minimax/h3-max/text-to-video',
    capabilities: { images: [startFrame(), endFrame(), referenceImages(4)] },
    routing: {
      kind: 'fal',
      text: 'minimax/h3-max/text-to-video',
      image: 'minimax/h3-max/image-to-video',
      reference: 'minimax/h3-max/reference-to-video',
      fields: { start: 'image_url', end: 'end_image_url', reference: 'reference_image_urls' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['480P', '768P', '1080P'], '768P'),
      durationChoices([5, 6, 8, 10, 12, 15], 5),
      aspectParam('aspect_ratio', MINIMAX_RATIOS, '16:9', { omitFor: ['i2x'] }),
      enumParam('prompt_expansion_mode', 'Prompt Expansion', ['balanced', 'quality'], 'balanced', {
        help: '"quality" spends up to ~30s rewriting the prompt before generating.',
      }),
      safetyChecker(),
      seedParam(),
    ],
  },
  {
    id: 'fal:minimax-h3',
    label: 'MiniMax H3',
    vendor: 'MiniMax',
    provider: 'fal',
    modality: 'video',
    description: 'MiniMax H3 with 2K/4K output.',
    docs: 'https://fal.ai/models/minimax/h3/text-to-video',
    capabilities: { images: [startFrame(), endFrame(), referenceImages(4)] },
    routing: {
      kind: 'fal',
      text: 'minimax/h3/text-to-video',
      image: 'minimax/h3/image-to-video',
      reference: 'minimax/h3/reference-to-video',
      fields: { start: 'image_url', end: 'end_image_url', reference: 'reference_image_urls' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['480P', '768P', '2K', '4K'], '2K'),
      durationChoices([5, 6, 8, 10, 12, 15], 5),
      aspectParam('aspect_ratio', MINIMAX_RATIOS, '16:9', { omitFor: ['i2x'] }),
      enumParam('prompt_expansion_mode', 'Prompt Expansion', ['balanced', 'quality'], 'balanced'),
      safetyChecker(),
      seedParam(),
    ],
  },
  {
    id: 'fal:hailuo-2.3',
    label: 'Hailuo 2.3',
    vendor: 'MiniMax',
    provider: 'fal',
    modality: 'video',
    badge: 'budget',
    description: 'Hailuo 2.3 standard — quick, inexpensive 6s or 10s clips.',
    docs: 'https://fal.ai/models/fal-ai/minimax/hailuo-2.3/standard/text-to-video',
    capabilities: { images: [startFrame()] },
    routing: {
      kind: 'fal',
      text: 'fal-ai/minimax/hailuo-2.3/standard/text-to-video',
      image: 'fal-ai/minimax/hailuo-2.3/standard/image-to-video',
      fields: { start: 'image_url' },
    },
    params: [
      durationSelect('duration', ['6', '10'], '6'),
      boolParam('prompt_optimizer', 'Prompt Optimizer', true),
    ],
  },

  // ── Alibaba Wan ───────────────────────────────────────────────────────────
  {
    id: 'fal:wan-3.0',
    label: 'Wan 3.0',
    vendor: 'Alibaba',
    provider: 'fal',
    modality: 'video',
    description: 'Wan 3.0 with audio, prompt expansion and 2–30s durations.',
    docs: 'https://fal.ai/models/alibaba/wan-3.0/text-to-video',
    capabilities: { images: [startFrame(), endFrame(), referenceImages(4)], audio: true },
    routing: {
      kind: 'fal',
      text: 'alibaba/wan-3.0/text-to-video',
      image: 'alibaba/wan-3.0/image-to-video',
      reference: 'alibaba/wan-3.0/reference-to-video',
      fields: { start: 'start_image_url', end: 'end_image_url', reference: 'reference_image_urls' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['480p', '720p', '1080p'], '1080p'),
      durationChoices([2, 4, 5, 6, 8, 10, 15, 20, 30], 5),
      aspectParam('aspect_ratio', WAN_RATIOS, 'adaptive'),
      boolParam('audio', 'Generate Audio', true),
      boolParam('enable_prompt_expansion', 'Prompt Expansion', true),
      boolParam('enable_thinking', 'Thinking', false),
      safetyChecker(),
      seedParam(),
    ],
  },
  {
    id: 'fal:wan-3.0-prime',
    label: 'Wan 3.0 Prime',
    vendor: 'Alibaba',
    provider: 'fal',
    modality: 'video',
    badge: 'pro',
    description: 'Highest-quality Wan 3.0 tier.',
    docs: 'https://fal.ai/models/alibaba/wan-3.0-prime/text-to-video',
    capabilities: { images: [startFrame(), endFrame(), referenceImages(4)], audio: true },
    routing: {
      kind: 'fal',
      text: 'alibaba/wan-3.0-prime/text-to-video',
      image: 'alibaba/wan-3.0-prime/image-to-video',
      reference: 'alibaba/wan-3.0-prime/reference-to-video',
      fields: { start: 'start_image_url', end: 'end_image_url', reference: 'reference_image_urls' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['480p', '720p', '1080p'], '1080p'),
      durationChoices([2, 4, 5, 6, 8, 10, 15], 5),
      aspectParam('aspect_ratio', WAN_RATIOS, 'adaptive'),
      boolParam('audio', 'Generate Audio', true),
      boolParam('enable_prompt_expansion', 'Prompt Expansion', true),
      boolParam('enable_thinking', 'Thinking', false),
      safetyChecker(),
      seedParam(),
    ],
  },

  // ── xAI ───────────────────────────────────────────────────────────────────
  {
    id: 'fal:grok-imagine-video-1.5',
    label: 'Grok Imagine Video 1.5',
    vendor: 'xAI',
    provider: 'fal',
    modality: 'video',
    description: 'xAI Grok Imagine 1.5 — fast, wide aspect-ratio coverage.',
    docs: 'https://fal.ai/models/xai/grok-imagine-video/v1.5/text-to-video',
    capabilities: { images: [startFrame(), referenceImages(4)] },
    routing: {
      kind: 'fal',
      text: 'xai/grok-imagine-video/v1.5/text-to-video',
      image: 'xai/grok-imagine-video/v1.5/image-to-video',
      reference: 'xai/grok-imagine-video/v1.5/reference-to-video',
      fields: { start: 'image_url', reference: 'reference_image_urls' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['480p', '720p', '1080p'], '720p', { omitFor: ['ref'] }),
      // The reference endpoint tops out at 720p.
      enumParam('resolution', 'Resolution', ['480p', '720p'], '720p', { omitFor: ['t2x', 'i2x'] }),
      durationChoices([1, 2, 4, 6, 8, 10, 12, 15], 6),
      aspectParam('aspect_ratio', ['16:9', '4:3', '3:2', '1:1', '2:3', '3:4', '9:16'], '16:9', { omitFor: ['i2x'] }),
    ],
  },

  // ── Black Forest Labs ─────────────────────────────────────────────────────
  {
    id: 'fal:flux-3-video',
    label: 'FLUX 3 Video',
    vendor: 'Black Forest Labs',
    provider: 'fal',
    modality: 'video',
    description: 'FLUX 3 video generation with audio, 5–20s.',
    docs: 'https://fal.ai/models/blackforestlabs/flux-3/text-to-video',
    capabilities: { images: [startFrame()], audio: true },
    routing: {
      kind: 'fal',
      text: 'blackforestlabs/flux-3/text-to-video',
      image: 'blackforestlabs/flux-3/image-to-video',
      fields: { start: 'image_url' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['720p', '1080p'], '720p'),
      durationEnum(['auto', '5', '6', '8', '10', '12', '15', '20'], 'auto'),
      aspectParam('aspect_ratio', ['auto', '21:9', '2:1', '16:9', '4:3', '1:1', '3:4', '9:16'], 'auto'),
      boolParam('generate_audio', 'Generate Audio', true),
      numberParam('safety_tolerance', 'Safety Tolerance', 0, 4, 2, { choices: [0, 1, 2, 3, 4] }),
    ],
  },

  // ── Lightricks ────────────────────────────────────────────────────────────
  {
    id: 'fal:ltx-2.3',
    label: 'LTX Video 2.3',
    vendor: 'Lightricks',
    provider: 'fal',
    modality: 'video',
    description: 'LTX 2.3 Pro — up to 2160p at 24–50 fps with audio.',
    docs: 'https://fal.ai/models/fal-ai/ltx-2.3/text-to-video',
    capabilities: { images: [startFrame(), endFrame()], audio: true },
    routing: {
      kind: 'fal',
      text: 'fal-ai/ltx-2.3/text-to-video',
      image: 'fal-ai/ltx-2.3/image-to-video',
      fields: { start: 'image_url', end: 'end_image_url' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['1080p', '1440p', '2160p'], '1080p'),
      durationChoices([6, 8, 10], 6),
      aspectParam('aspect_ratio', VEO_RATIOS, '16:9', { omitFor: ['i2x'] }),
      numberParam('fps', 'Frame Rate', 24, 50, 25, { choices: [24, 25, 48, 50] }),
      boolParam('generate_audio', 'Generate Audio', true),
    ],
  },

  // ── PixVerse ──────────────────────────────────────────────────────────────
  {
    id: 'fal:pixverse-v6',
    label: 'PixVerse V6',
    vendor: 'PixVerse',
    provider: 'fal',
    modality: 'video',
    description: 'PixVerse V6 with styles, multi-clip and 1–15s durations.',
    docs: 'https://fal.ai/models/fal-ai/pixverse/v6/text-to-video',
    capabilities: { images: [startFrame(), referenceImages(4)] },
    routing: {
      kind: 'fal',
      text: 'fal-ai/pixverse/v6/text-to-video',
      image: 'fal-ai/pixverse/v6/image-to-video',
      reference: 'fal-ai/pixverse/v6/reference-to-video',
      fields: { start: 'image_url', reference: 'image_references' },
    },
    params: [
      enumParam('resolution', 'Resolution', ['360p', '540p', '720p', '1080p'], '720p'),
      durationChoices([1, 3, 5, 8, 10, 12, 15], 5),
      aspectParam('aspect_ratio', ['16:9', '4:3', '1:1', '3:4', '9:16', '2:3', '3:2', '21:9'], '16:9', {
        omitFor: ['i2x'],
      }),
      boolParam('generate_audio_switch', 'Generate Audio', false),
      boolParam('generate_multi_clip_switch', 'Multi-clip', false, { omitFor: ['ref'] }),
      enumParam('style', 'Style', ['none', 'anime', '3d_animation', 'clay', 'comic', 'cyberpunk'], 'none', {
        wide: true,
        omitWhenDefault: true,
        omitFor: ['ref'],
      }),
      enumParam('thinking_type', 'Thinking', ['auto', 'enabled', 'disabled'], 'auto', { omitFor: ['ref'] }),
      negativePrompt('', { omitFor: ['ref'] }),
      seedParam(),
    ],
  },

  // ── Direct provider APIs ──────────────────────────────────────────────────
  {
    id: 'google:veo-3.1',
    label: 'Veo 3.1',
    vendor: 'Google',
    provider: 'google',
    modality: 'video',
    description: 'Veo 3.1 straight from the Gemini API: first/last frame plus up to 3 asset references.',
    docs: 'https://ai.google.dev/gemini-api/docs/veo',
    capabilities: { images: [startFrame(), endFrame(), referenceImages(3)], audio: true },
    routing: { kind: 'native', model: 'veo-3.1-generate-preview' },
    params: [
      enumParam('resolution', 'Resolution', ['720p', '1080p', '4k'], '720p'),
      durationSelect('durationSeconds', ['4', '6', '8'], '8'),
      aspectParam('aspectRatio', VEO_RATIOS, '16:9'),
      enumParam('personGeneration', 'People', ['allow_all', 'allow_adult'], 'allow_all'),
      negativePrompt(),
    ],
  },
  {
    id: 'google:veo-3.1-lite',
    label: 'Veo 3.1 Lite',
    vendor: 'Google',
    provider: 'google',
    modality: 'video',
    badge: 'budget',
    description: 'Cheapest Veo 3.1 tier from the Gemini API, with first/last frame.',
    docs: 'https://ai.google.dev/gemini-api/docs/veo',
    capabilities: { images: [startFrame(), endFrame()], audio: true },
    routing: { kind: 'native', model: 'veo-3.1-lite-generate-preview' },
    params: [
      enumParam('resolution', 'Resolution', ['720p', '1080p'], '720p'),
      durationSelect('durationSeconds', ['4', '6', '8'], '8'),
      aspectParam('aspectRatio', VEO_RATIOS, '16:9'),
      negativePrompt(),
    ],
  },
  {
    id: 'openai:sora-2',
    label: 'Sora 2',
    vendor: 'OpenAI',
    provider: 'openai',
    modality: 'video',
    description: 'Sora 2 through the OpenAI videos API using your OpenAI key.',
    docs: 'https://platform.openai.com/docs/api-reference/videos',
    capabilities: { images: [startFrame()], audio: true },
    routing: { kind: 'native', model: 'sora-2' },
    params: [
      durationSelect('seconds', ['4', '8', '12'], '4'),
      enumParam('size', 'Size', ['1280x720', '720x1280', '1792x1024', '1024x1792'], '1280x720', {
        control: 'select',
      }),
    ],
  },
  {
    id: 'openai:sora-2-pro',
    label: 'Sora 2 Pro',
    vendor: 'OpenAI',
    provider: 'openai',
    modality: 'video',
    badge: 'pro',
    description: 'Higher-fidelity Sora 2 tier.',
    docs: 'https://platform.openai.com/docs/api-reference/videos',
    capabilities: { images: [startFrame()], audio: true },
    routing: { kind: 'native', model: 'sora-2-pro' },
    params: [
      durationSelect('seconds', ['4', '8', '12'], '4'),
      enumParam('size', 'Size', ['1280x720', '720x1280', '1792x1024', '1024x1792'], '1280x720', {
        control: 'select',
      }),
    ],
  },
  {
    id: 'modelark:seedance-2.5',
    label: 'Seedance 2.5',
    vendor: 'ByteDance',
    provider: 'modelark',
    modality: 'video',
    description: 'Seedance 2.5 straight from BytePlus ModelArk.',
    docs: 'https://docs.byteplus.com/en/docs/ModelArk/1520757',
    capabilities: { images: [startFrame(), endFrame(), referenceImages(4)], audio: true },
    routing: { kind: 'native', model: 'dreamina-seedance-2-5-260628' },
    params: [
      enumParam('resolution', 'Resolution', ['480p', '720p', '1080p'], '720p'),
      durationChoices([4, 5, 6, 8, 10, 12, 15, 20, 25, 30], 5),
      aspectParam('ratio', ['adaptive', '21:9', '16:9', '4:3', '1:1', '3:4', '9:16'], 'adaptive', {
        omitFor: ['i2x'],
        help: 'With a start frame connected, ModelArk requires the ratio to follow the image.',
      }),
      boolParam('generate_audio', 'Generate Audio', true),
      boolParam('camera_fixed', 'Fixed Camera', false),
      boolParam('watermark', 'Watermark', false),
      seedParam(),
    ],
  },
  {
    id: 'modelark:seedance-2.0',
    label: 'Seedance 2.0',
    vendor: 'ByteDance',
    provider: 'modelark',
    modality: 'video',
    description: 'Seedance 2.0 from BytePlus ModelArk.',
    docs: 'https://docs.byteplus.com/en/docs/ModelArk/1520757',
    capabilities: { images: [startFrame(), endFrame(), referenceImages(4)], audio: true },
    routing: { kind: 'native', model: 'dreamina-seedance-2-0-260128' },
    params: [
      enumParam('resolution', 'Resolution', ['480p', '720p', '1080p'], '720p'),
      durationChoices([4, 5, 6, 8, 10, 12, 15], 5),
      aspectParam('ratio', ['adaptive', '21:9', '16:9', '4:3', '1:1', '3:4', '9:16'], 'adaptive', {
        omitFor: ['i2x'],
      }),
      boolParam('generate_audio', 'Generate Audio', true),
      boolParam('camera_fixed', 'Fixed Camera', false),
      boolParam('watermark', 'Watermark', false),
      seedParam(),
    ],
  },
  {
    id: 'kling:3.0',
    label: 'Kling 3.0',
    vendor: 'Kuaishou',
    provider: 'kling',
    modality: 'video',
    description: 'Kling 3.0 via the official API. Needs the local dev proxy (no CORS).',
    docs: 'https://kling.ai/document-api/api/video/3-0-omni/text-to-video',
    capabilities: { images: [startFrame(), endFrame()], audio: true },
    routing: { kind: 'native', model: 'kling-3.0' },
    params: [
      enumParam('resolution', 'Resolution', ['720p', '1080p', '4k'], '1080p'),
      durationChoices([3, 4, 5, 6, 8, 10, 12, 15], 5),
      aspectParam('aspect_ratio', KLING_RATIOS, '16:9', { omitFor: ['i2x'] }),
      enumParam('audio', 'Audio', ['off', 'native'], 'off'),
      boolParam('multi_shot', 'Multi-shot', true),
    ],
  },
  {
    id: 'kling:3.0-turbo',
    label: 'Kling 3.0 Turbo',
    vendor: 'Kuaishou',
    provider: 'kling',
    modality: 'video',
    badge: 'fast',
    description: 'Faster Kling 3.0 tier via the official API (dev proxy required).',
    docs: 'https://kling.ai/document-api/api/video/3-0-turbo/text-to-video',
    capabilities: { images: [startFrame(), endFrame()], audio: true },
    routing: { kind: 'native', model: 'kling-3.0-turbo' },
    params: [
      enumParam('resolution', 'Resolution', ['720p', '1080p', '4k'], '1080p'),
      durationChoices([3, 4, 5, 6, 8, 10, 12, 15], 5),
      aspectParam('aspect_ratio', KLING_RATIOS, '16:9', { omitFor: ['i2x'] }),
      enumParam('audio', 'Audio', ['off', 'native'], 'off'),
    ],
  },
  {
    id: 'kling:2.6',
    label: 'Kling 2.6',
    vendor: 'Kuaishou',
    provider: 'kling',
    modality: 'video',
    description: 'Kling 2.6 via the official API (dev proxy required).',
    docs: 'https://kling.ai/document-api/api/video/2-6/text-to-video',
    capabilities: { images: [startFrame(), endFrame()], audio: true },
    routing: { kind: 'native', model: 'kling-2.6' },
    params: [
      enumParam('resolution', 'Resolution', ['720p', '1080p'], '1080p'),
      durationChoices([3, 4, 5, 6, 8, 10], 5),
      aspectParam('aspect_ratio', KLING_RATIOS, '16:9', { omitFor: ['i2x'] }),
      enumParam('audio', 'Audio', ['off', 'native'], 'off'),
    ],
  },
];
